 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package script;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author acebi
 */
public class orderitem extends javax.swing.JPanel {
    /**
     * Creates new form OrderDetail
     */
    private mainPage parentFrame; 
    
    public orderitem(mainPage parent) {
        this.parentFrame = parent;
        initComponents();
    }
    
    public void setOrderData(String orderId, String orderName, String date, String status, String price) {
        jLabel1.setText(orderId);
        jLabel2.setText(orderName);
        jLabel3.setText(date);
        jLabel4.setText(status);
        jLabel5.setText(price);
    }
//    public void setDetailOrderData(String orderId, String orderName, String date, String status, String price,String picturePath) {
//        jLabel1.setText(orderId);
//        jLabel2.setText(orderName);
//        jLabel3.setText(date);
//        jLabel4.setText(status);
//        jLabel5.setText(price);
////        jLabel6.setIcon(new ImageIcon(picture))
    /// @param orderId;
    /// @param picturePath
    /// @param orderName
    /// @param date
    /// @param status
    /// @param price
//    setScaledIcon(jLabel6, picturePath, 65, 65);
//    }
    public void setDetailOrderData(String orderId, String picturePath, String orderName, String date, String status) {
        jLabel1.setText(orderId);
        setScaledIcon(jLabel2, picturePath, 65, 65);
        jLabel3.setText(orderName);
        jLabel4.setText(date);
        jLabel5.setText(status);

//        jLabel6.setIcon(new ImageIcon(picture));
    }

    private void setScaledIcon(javax.swing.JLabel label, String path, int w, int h) {
        try {
            java.net.URL url = getClass().getResource(path);
            if (url == null) {
                System.out.println("Không tìm thấy icon: " + path);
                label.setIcon(null);
                return;
            }

            ImageIcon icon = new ImageIcon(url);
            Image img = icon.getImage().getScaledInstance(w, h, Image.SCALE_SMOOTH);
            label.setIcon(new ImageIcon(img));

        } catch (Exception e) {
            e.printStackTrace();
        }
    }    
//    public void hideActionButtons() {
//        // Xóa icon
//        // Đặt lại icon khác hoặc xóa icon
////        try {
////            jLabel6.setIcon(new ImageIcon(getClass().getResource("/asset/picture/product/AYTT001-2.jpg")));
////        } catch (Exception e) {
////            System.out.println("Lỗi load icon: " + e);
////        }
//        jLabel7.setIcon(null);
////        jLabel6.setIcon(null);
//
//        // Xóa text nếu có
//        jLabel6.setText("");
//        jLabel7.setText("");
//
//        // Tắt click
//        jLabel6.setCursor(null);
//        jLabel7.setCursor(null);
//
//        for (java.awt.event.MouseListener ml : jLabel6.getMouseListeners()) {
//            jLabel6.removeMouseListener(ml);
//        }
//        for (java.awt.event.MouseListener ml : jLabel7.getMouseListeners()) {
//            jLabel7.removeMouseListener(ml);
//        }
//    }

    public void hideActionButtons() {

//    jLabel6.setText("");
    jLabel7.setText("");

    jLabel6.setIcon(null);
    jLabel7.setIcon(null);

    jLabel6.setCursor(null);
    jLabel7.setCursor(null);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("jLabel1");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        jLabel1.setOpaque(true);
        add(jLabel1);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setOpaque(true);
        add(jLabel2);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("jLabel3");
        jLabel3.setOpaque(true);
        add(jLabel3);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("jLabel4");
        jLabel4.setOpaque(true);
        add(jLabel4);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("jLabel5");
        jLabel5.setOpaque(true);
        add(jLabel5);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0, 0, -5));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/picture/user/menu.png"))); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));
        jPanel1.add(jLabel6);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/picture/user/exit.png"))); // NOI18N
        jPanel1.add(jLabel7);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        parentFrame.showChiTietDonHang();
// TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
