/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;

/**
 *
 * @author acebi
 */
public class OrderDetail extends javax.swing.JFrame {

    /**
     * Creates new form Order
     */
//    private JPanel headerPanel;
//    private JPanel listPanel;
//    private JScrollPane scrollPane;

    public OrderDetail() {
        initComponents();
        loadOrderList(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sanpham = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ListSanPham = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.BorderLayout(0, 5));

        Sanpham.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Sanpham.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setText("ProductID#");
        Sanpham.add(jLabel1);

        jLabel2.setText("ProductName");
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        Sanpham.add(jLabel2);

        jLabel3.setText("Size");
        jLabel3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        Sanpham.add(jLabel3);

        jLabel4.setText("Color");
        jLabel4.setVerifyInputWhenFocusTarget(false);
        jLabel4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        Sanpham.add(jLabel4);

        jLabel5.setText("Price");
        jLabel5.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        Sanpham.add(jLabel5);

        getContentPane().add(Sanpham, java.awt.BorderLayout.NORTH);

        ListSanPham.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ListSanPham.setLayout(new javax.swing.BoxLayout(ListSanPham, javax.swing.BoxLayout.Y_AXIS));
        getContentPane().add(ListSanPham, java.awt.BorderLayout.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 60, 5));

        jLabel6.setText("đang xác thực");
        jPanel1.add(jLabel6);

        jLabel7.setText("đã đóng gói");
        jPanel1.add(jLabel7);

        jLabel8.setText("đã giao cho đơn vị vận chuyển");
        jPanel1.add(jLabel8);

        jLabel9.setText("đang giao hàng");
        jPanel1.add(jLabel9);

        jLabel10.setText("hàng đã được giao");
        jPanel1.add(jLabel10);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
//    private void initComponents() {
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//        setTitle("Order List");
//        setSize(1200, 700);
//        setLocationRelativeTo(null); // Căn giữa màn hình
//        getContentPane().setLayout(new java.awt.BorderLayout(0, 5));
//
//        // Header
//        headerPanel = new javax.swing.JPanel();
//        headerPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
//        headerPanel.setLayout(new java.awt.GridLayout(1, 5));
//
//        JLabel lblId = new JLabel("Order ID#", SwingConstants.CENTER);
//        JLabel lblName = new JLabel("Order name", SwingConstants.CENTER);
//        JLabel lblDate = new JLabel("Date", SwingConstants.CENTER);
//        JLabel lblStatus = new JLabel("Status", SwingConstants.CENTER);
//        JLabel lblPrice = new JLabel("Price", SwingConstants.CENTER);
//
//        headerPanel.add(lblId);
//        headerPanel.add(lblName);
//        headerPanel.add(lblDate);
//        headerPanel.add(lblStatus);
//        headerPanel.add(lblPrice);
//
//        getContentPane().add(headerPanel, java.awt.BorderLayout.NORTH);
//
//        // Panel chứa danh sách đơn hàng
//        listPanel = new javax.swing.JPanel();
//        listPanel.setLayout(new javax.swing.BoxLayout(listPanel, javax.swing.BoxLayout.Y_AXIS));
//        listPanel.setBackground(new java.awt.Color(240, 240, 240));
//
//        // ScrollPane bao quanh listPanel
//        scrollPane = new javax.swing.JScrollPane(listPanel);
//        scrollPane.setBorder(null);
//        scrollPane.getVerticalScrollBar().setUnitIncrement(16); // cuộn mượt hơn
//
//        getContentPane().add(scrollPane, java.awt.BorderLayout.CENTER);
//
//        pack();
//    }
    
        private void loadOrderList() {
        // Dữ liệu mô phỏng
        String[][] orders = {
                {"#001", "Giày Nike Air", "2025-10-27", "Delivered", "1.200.000"},
                {"#002", "Adidas UltraBoost", "2025-10-25", "Pending", "2.000.000"},
                {"#003", "Converse Classic", "2025-10-24", "Canceled", "950.000"},
                {"#004", "Vans Old Skool", "2025-10-20", "Shipped", "1.100.000"},
                {"#005", "Vans Old Skool", "2025-10-20", "Shipped", "1.100.000"},
                {"#006", "Vans Old Skool", "2025-10-20", "Shipped", "1.100.000"}
        };

        for (String[] o : orders) {
            OrderList item = new OrderList();
            item.setOrderData(o[0], o[1], o[2], o[3], o[4]);

            // Kéo full ngang + padding đẹp
            item.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, 50));
            item.setBorder(BorderFactory.createLineBorder(java.awt.Color.GRAY));

            ListSanPham.add(item);
            ListSanPham.add(Box.createVerticalStrut(5)); // khoảng cách giữa các dòng
        }

        ListSanPham.revalidate();
        ListSanPham.repaint();
    }
        
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ListSanPham;
    private javax.swing.JPanel Sanpham;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
