                            /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author acebi
 */
public class OrderList extends javax.swing.JPanel {

    /**
     * Creates new form OrderDetail
     */
    public OrderList() {
        initComponents();
    }
    
    public void setOrderData(String orderId, String orderName, String date, String status, String price) {
        jLabel1.setText(orderId);
        jLabel2.setText(orderName);
        jLabel3.setText(date);
        jLabel4.setText(status);
        jLabel5.setText(price);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setBackground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("jLabel1");
        jLabel1.setOpaque(true);
        add(jLabel1);

        jLabel2.setBackground(new java.awt.Color(255, 102, 102));
        jLabel2.setText("jLabel2");
        jLabel2.setOpaque(true);
        add(jLabel2);

        jLabel3.setBackground(new java.awt.Color(255, 102, 102));
        jLabel3.setText("jLabel3");
        jLabel3.setOpaque(true);
        add(jLabel3);

        jLabel4.setBackground(new java.awt.Color(255, 102, 102));
        jLabel4.setText("jLabel4");
        jLabel4.setOpaque(true);
        add(jLabel4);

        jLabel5.setBackground(new java.awt.Color(255, 102, 102));
        jLabel5.setText("jLabel5");
        jLabel5.setOpaque(true);
        add(jLabel5);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
